import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "./components/providers/theme-provider";
import { ModalProvider } from "./components/providers/modal-provider";


const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Echo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl='/'>
      <html lang="en" suppressHydrationWarning >
        <body className={font.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
          >
            <ModalProvider />
            {children}
          </ThemeProvider>


        </body>
      </html>
    </ClerkProvider>
  );
}
